version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: 
        context: ./flask_app
        dockerfile: flask.dockerfile
    ports:
      - "8000:8000"
    command: pipenv run gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
  
  nginx:
    container_name: nginx
    restart: always
    build: 
        context: ./nginx
        dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask_app
